Repository algorandfoundation/algo-models, pull requests merged in 2025-02, with the labels that each got.

#18 fix: package exports
  lib/algorand.transaction.acfg.ts
  lib/algorand.transaction.afrz.ts
  lib/algorand.transaction.axfer.ts
  lib/algorand.transaction.crafter.spec.ts
  lib/algorand.transaction.header.ts
  lib/algorand.transaction.keyreg.ts
  lib/algorand.transaction.pay.ts
  lib/algorand.transaction.ts
  lib/index.ts
  package-lock.json
  package.json
Labels: bug

#19 BIGINTs and Schema validation updates
  lib/algorand.asset.params.ts
  lib/algorand.encoder.spec.ts
  lib/algorand.encoder.ts
  lib/algorand.transaction.acfg.ts
  lib/algorand.transaction.afrz.ts
  lib/algorand.transaction.axfer.ts
  lib/algorand.transaction.crafter.spec.ts
  lib/algorand.transaction.crafter.ts
  lib/algorand.transaction.header.ts
  lib/algorand.transaction.keyreg.ts
  lib/algorand.transaction.pay.ts
  lib/schemas/acfg.transaction.json
  lib/schemas/afrz.transaction.json
  lib/schemas/asset.params.json
  lib/schemas/axfer.transaction.json
  lib/schemas/keyreg.transaction.online.json
  lib/schemas/pay.transaction.json
  lib/schemas/transaction.header.json
  package.json
  tsconfig.cjs.json
Labels: enhancement

#20 npm version bump
  package.json
Labels: documentation, enhancement

#11 ci: conventional commits
  .github/workflows/CI.yml
  .github/workflows/release.yml
  .gitignore
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: enhancement

#21 feat: Add computeGroupId support in Encoder
  lib/algorand.encoder.spec.ts
  lib/algorand.encoder.ts
  lib/algorand.transaction.ts
  package-lock.json
  package.json
  tsconfig.esm.json
Labels: enhancement, feature
